self.config = {
  "version": "2.0.0.103",
  "pageTitle": "Housebird Games",
  "cookieIdentifier": "HousebirdGames",
  "foundationYear": 2020,
  "pageDescription": "Explore calming games, thrilling quests, intriguing puzzles, and innovative prototypes on various platforms for a joyful and relaxing gaming experience.",
  "localhostPath": "/housebird_games",
  "excludedPaths": [
    "/database/logout.php",
    "/calculator",
    "/timeless-tales",
    "/minigame-collection",
    "/html-table-csv-converter",
    "/stormworks-creations-manager",
    "/creations-manager",
    "/creations-manager-staging",
    "/game-servers"
  ],
  "pwaExcludedPaths": [],
  "openCookiePopupAtPageLoad": false,
  "showNewUpdateNotes": false,
  "maintenanceModeWithFailedBackend": false,
  "enableInputValidation": true,
  "enableImageComparisonSliders": true,
  "enableInfoBar": false,
  "userLoginEnabled": true,
  "redirect404ToRoot": false,
  "appIcon": "img/app-icons/icon",
  "trustedImageDomains": [],
  "useMouseDown": true,
  "useFlexPopups": false,
  "backNavigationClosesPopups": true,
  "scrollPositionRecallLimit": 20,
  "domainPath": ""
};